#!/bin/bash
#SBATCH --job-name=###JOB_NAME###
#SBATCH --partition=3090-gcondo
#SBATCH --nodes=1
#SBATCH --cpus-per-task=6
#SBATCH --mem=125G
#SBATCH --time=24:00:00
#SBATCH --gres=gpu:1
#SBATCH --signal=SIGUSR1@90
#SBATCH --chdir=/users/cjmok/automated-perspective-sculptor
#SBATCH --output=./logs/%x.%j.out
#SBATCH --error=./logs/%x.%j.err
###SBATCH_ARGS###

source /oscar/home/cjmok/.bashrc
conda activate myenv

ulimit -n 50000


###COMMANDS###
