# ablation_acm_scf_ablation — generated by slurm/generate_jobs.py
python run_ablation.py --target1 images/acm.png --target2 images/scf.png --mode ablation --trials 3 --steps 2000 --device cuda --output-dir 'results/slurm/###TIMESTAMP###/ablation_acm_scf_ablation'
