# ablation_horse_circle_full — generated by slurm/generate_jobs.py
python run_ablation.py --target1 images/horse.png --target2 images/circle.png --mode full --trials 3 --steps 2000 --swept-resolution 256 --device cuda --output-dir 'results/slurm/###TIMESTAMP###/ablation_horse_circle_full'
