# ablation_cat_face_bass_ablation — generated by slurm/generate_jobs.py
python run_ablation.py --target1 images/cat_face.png --target2 images/bass.png --mode ablation --trials 3 --steps 2000 --device cuda --output-dir 'results/slurm/###TIMESTAMP###/ablation_cat_face_bass_ablation'
