# ablation_sun_moon_full — generated by slurm/generate_jobs.py
python run_ablation.py --target1 images/sun.png --target2 images/moon.png --mode full --trials 3 --steps 2000 --device cuda --output-dir 'results/slurm/###TIMESTAMP###/ablation_sun_moon_full'
