# ablation_sun_moon_ablation — generated by slurm/generate_jobs.py
python run_ablation.py --target1 images/sun.png --target2 images/moon.png --mode ablation --trials 3 --steps 2000 --swept-resolution 256 --device cuda --output-dir 'results/slurm/###TIMESTAMP###/ablation_sun_moon_ablation'
