# ablation_water_fire_ablation — generated by slurm/generate_jobs.py
python run_ablation.py --target1 images/water.png --target2 images/fire.png --mode ablation --trials 3 --steps 2000 --device cuda --output-dir 'results/slurm/###TIMESTAMP###/ablation_water_fire_ablation'
