# comparison_horse_circle_basic — generated by slurm/generate_jobs.py
python run_ablation.py --target1 images/horse.png --target2 images/circle.png --no-srd --trials 3 --steps 2000 --device cuda --output-dir 'results/slurm/###TIMESTAMP###/comparison_horse_circle_basic'
