# comparison_cat_face_bass_basic — generated by slurm/generate_jobs.py
python run_ablation.py --target1 images/cat_face.png --target2 images/bass.png --no-srd --trials 3 --steps 2000 --device cuda --output-dir 'results/slurm/###TIMESTAMP###/comparison_cat_face_bass_basic'
