# comparison_water_fire_annealing — generated by slurm/generate_jobs.py
python run_ablation.py --target1 images/water.png --target2 images/fire.png --no-srd --simulated-annealing --trials 3 --steps 2000 --device cuda --output-dir 'results/slurm/###TIMESTAMP###/comparison_water_fire_annealing'
