# comparison_acm_scf_annealing — generated by slurm/generate_jobs.py
python run_ablation.py --target1 images/acm.png --target2 images/scf.png --no-srd --simulated-annealing --trials 3 --steps 2000 --device cuda --output-dir 'results/slurm/###TIMESTAMP###/comparison_acm_scf_annealing'
