"""Regenerate the SLURM job payload files in this folder.

Creates one .sh payload per experiment:

    ablation_<pair>_<setting>.sh      full / ablation        (submit_ablations.py settings)
    comparison_<pair>_<setting>.sh    basic / srd / annealing (submit_comparison.py settings)
    patchsize_<pair>_<n>.sh           SRD vs. base at n initial patches

The files contain only the commands; #SBATCH headers come from a template
(e.g. the repo-root ccv-3090 file) when submitted with submit_job.py:

    python submit_job.py ccv-3090 --yes slurm/ablation_horse_circle_full.sh

###TIMESTAMP### in the payload is replaced by submit_job.py at submission
time, so each submission batch writes to its own results/slurm/<timestamp>/
folder (aggregate it with:
python submit_ablations.py --sweep-name slurm/<timestamp> --collect).

Rerun after changing image pairs or run settings:

    python slurm/generate_jobs.py [--trials 3] [--steps 2000]
"""

from __future__ import annotations

import argparse
import shlex
import sys
from pathlib import Path

_SLURM_DIR = Path(__file__).resolve().parent
_PROJECT_ROOT = _SLURM_DIR.parent
sys.path.insert(0, str(_PROJECT_ROOT))

from submit_ablations import IMAGE_PAIRS, RUN_SETTINGS as ABLATION_SETTINGS  # noqa: E402
from submit_comparison import RUN_SETTINGS as COMPARISON_SETTINGS  # noqa: E402

EXPERIMENTS = {
    "ablation": (ABLATION_SETTINGS, ["full", "ablation"]),
    "comparison": (COMPARISON_SETTINGS, ["basic", "srd"]),
}

# Initial patch counts for the patchsize_<pair>_<n> jobs. One job per size
# keeps each payload to a single compare_srd.py run pair (SRD vs. base), so
# nothing approaches the template walltime.
PATCH_SIZES = [5, 10, 20, 30]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--trials", type=int, default=3)
    parser.add_argument("--steps", type=int, default=2000)
    parser.add_argument(
        "--patch-steps",
        type=int,
        default=1000,
        help="Steps for the patchsize_* jobs (each runs SRD and base back to back).",
    )
    parser.add_argument(
        "--swept-resolution",
        type=int,
        default=256,
        help="Swept-volume grid resolution, pinned in the ablation/comparison payloads.",
    )
    args = parser.parse_args()

    written = []
    for experiment, (settings, defaults) in EXPERIMENTS.items():
        for pair, (target1, target2) in IMAGE_PAIRS.items():
            for setting in defaults:
                job_name = f"{experiment}_{pair}_{setting}"
                command = shlex.join([
                    "python", "run_ablation.py",
                    "--target1", f"images/{target1}",
                    "--target2", f"images/{target2}",
                    *settings[setting],
                    "--trials", str(args.trials),
                    "--steps", str(args.steps),
                    "--swept-resolution", str(args.swept_resolution),
                    "--device", "cuda",
                    "--output-dir", f"results/slurm/###TIMESTAMP###/{job_name}",
                ])
                path = _SLURM_DIR / f"{job_name}.sh"
                path.write_text(
                    f"# {job_name} — generated by slurm/generate_jobs.py\n"
                    f"{command}\n",
                    encoding="utf-8",
                )
                written.append(path.name)

    for pair, (target1, target2) in IMAGE_PAIRS.items():
        for patch_size in PATCH_SIZES:
            job_name = f"patchsize_{pair}_{patch_size}"
            command = shlex.join([
                "python", "compare_srd_patch_sizes.py",
                "--target1", f"images/{target1}",
                "--target2", f"images/{target2}",
                "--patch-sizes", str(patch_size),
                "--trials", str(args.trials),
                "--steps", str(args.patch_steps),
                "--output-dir", f"results/slurm/###TIMESTAMP###/{job_name}",
            ])
            path = _SLURM_DIR / f"{job_name}.sh"
            path.write_text(
                f"# {job_name} — generated by slurm/generate_jobs.py\n"
                f"{command}\n",
                encoding="utf-8",
            )
            written.append(path.name)

    print(f"Wrote {len(written)} job files to {_SLURM_DIR}/:")
    for name in written:
        print(f"  {name}")


if __name__ == "__main__":
    main()
