# patchsize_sun_moon_5 — generated by slurm/generate_jobs.py
python compare_srd_patch_sizes.py --target1 images/sun.png --target2 images/moon.png --patch-sizes 5 --trials 3 --steps 1000 --output-dir 'results/slurm/###TIMESTAMP###/patchsize_sun_moon_5'
