# patchsize_horse_circle_10 — generated by slurm/generate_jobs.py
python compare_srd_patch_sizes.py --target1 images/horse.png --target2 images/circle.png --patch-sizes 10 --trials 3 --steps 1000 --output-dir 'results/slurm/###TIMESTAMP###/patchsize_horse_circle_10'
