# patchsize_cat_face_bass_20 — generated by slurm/generate_jobs.py
python compare_srd_patch_sizes.py --target1 images/cat_face.png --target2 images/bass.png --patch-sizes 20 --trials 3 --steps 1000 --output-dir 'results/slurm/###TIMESTAMP###/patchsize_cat_face_bass_20'
