# patchsize_acm_scf_30 — generated by slurm/generate_jobs.py
python compare_srd_patch_sizes.py --target1 images/acm.png --target2 images/scf.png --patch-sizes 30 --trials 3 --steps 1000 --output-dir 'results/slurm/###TIMESTAMP###/patchsize_acm_scf_30'
